# Generated by Django 4.2.1 on 2023-05-24 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BuyIn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.IntegerField(unique=True)),
                ("small_blind", models.IntegerField()),
                ("big_blind", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="TableSize",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=45, unique=True)),
                ("seats", models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Table",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("seats", models.JSONField()),
                ("open_seat", models.BooleanField(default=True)),
                ("n_players", models.IntegerField(default=0)),
                (
                    "buy_in",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="poker.buyin"
                    ),
                ),
                (
                    "table_size",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="poker.tablesize",
                    ),
                ),
            ],
        ),
    ]
